// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDqCVwVviUqLOOxcxB4yNFuX0p2u_J-s',
    appId: '1:661800619917:web:e7ea56c35729c73a01f7c4',
    messagingSenderId: '661800619917',
    projectId: 'ourapp-94af9',
    authDomain: 'ourapp-94af9.firebaseapp.com',
    storageBucket: 'ourapp-94af9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZz4s_5dZkxFOUFFC6HOx55fMduZB4J_8',
    appId: '1:661800619917:android:7ed186cc57b8b18701f7c4',
    messagingSenderId: '661800619917',
    projectId: 'ourapp-94af9',
    storageBucket: 'ourapp-94af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8IByjx52o7-q5K02vZ032sR1fMPfVUwQ',
    appId: '1:661800619917:ios:7f1c3cc66816761c01f7c4',
    messagingSenderId: '661800619917',
    projectId: 'ourapp-94af9',
    storageBucket: 'ourapp-94af9.appspot.com',
    iosBundleId: 'com.example.ourapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8IByjx52o7-q5K02vZ032sR1fMPfVUwQ',
    appId: '1:661800619917:ios:7f1c3cc66816761c01f7c4',
    messagingSenderId: '661800619917',
    projectId: 'ourapp-94af9',
    storageBucket: 'ourapp-94af9.appspot.com',
    iosBundleId: 'com.example.ourapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDqCVwVviUqLOOxcxB4yNFuX0p2u_J-s',
    appId: '1:661800619917:web:0bee0f5e672dd7c001f7c4',
    messagingSenderId: '661800619917',
    projectId: 'ourapp-94af9',
    authDomain: 'ourapp-94af9.firebaseapp.com',
    storageBucket: 'ourapp-94af9.appspot.com',
  );
}
